export enum RoleName {
  ADMIN = 'ADMIN',
  MANAGE = 'MANAGE',
  STAFF_ACADEMIC = 'STAFF_ACADEMIC',
  STAFF_GENERAL = 'STAFF_GENERAL',
  TEACHER_PART_TIME = 'TEACHER_PART_TIME',
  TEACHER_FULL_TIME = 'TEACHER_FULL_TIME',
  RECEPTIONIST = 'RECEPTIONIST',
  STUDENT = 'STUDENT',
}
